baseurl = "https://cm21.netlify.app/"
title = "Ellie Marvin"
theme = "hugo-theme-nix"
languageCode = "en-us"
nocomments = true

[menu]
  [[menu.header]]
    name = "posts"
    weight = 0
    url = "post"
  [[menu.header]]
    name = "about"
    weight = 1
    url = "about/project"

[params]
  GithubID = "semarvin"
  LinkedInID = "ellie-marvin"
  Email = "sem14t@my.fsu.edu"
  Name = "Ellie Marvin"
  HeaderUsername = "sem14t"
  HeaderHostname = "my.fsu.edu"
  About = "I am currently a graduate student at Florida State University working on my MA in Digital Humanities. In May of 2019, I earned my BA from FSU and graduated Summa Cum Laude. I double majored in English and Humanities with a minor in Film Studies. My interests and hobbies include writing, editing, graphic design, art, photography, and film. I am currently based out of Tallahassee and will be graduating in April 2021. You can contact me via the links above. This website is dedicated to my research regarding Artificial Intelligence and Surrealism."
  ProfilePicture = "/ellie_marvin.png"
  Favicon = "/favicon.ico"

