[build]
  publish = "public"
  command = "hugo"

[build.environment]
  HUGO_THEME = "hugo-theme-nix"
  HUGO_VERSION = "0.62.2"

[context.production.environment]
  HUGO_BASEURL = "https://cm21.netlify.app/"

[context.deploy-preview]
  command = "hugo"

[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=600"

[[headers]]
  for = "*.(css|js|woff|woff2|ttf|png|jpg|jpeg)"
  [headers.values]
    Cache-Control = "public, max-age=2592000"
