theme = "edidor"
title = "Edidor Demo"
baseurl = "https://your site url"
AuthorName = "Jon Doe"
# place your logo file to ./static/images to set logo

# i18n is not completed yet, help is appreciated.
languageCode = "en"
defaultContentLanguage = "en"
# you may not need this
hasCJKLanguage = true


# ----- feel free change these settings, those are not tied to this theme --
paginate = 5
enableEmoji = true

# to have better preview
buildDrafts = "true"
# helpful if you want to edit the site or theme code
disableFastRender = true
# --------------------------------------------------------------------------

disqusShortname = "your disqus short name"
googleAnalytics = "your ga id"

# social link in the footer, change it to "" hide it
[social]
    github = " "
    facebook = " "
    twitter = " "
    behance = " "
    email = " "

# author, title, description are used in the home page, you can embed html tag in description
[params]
    # will use AuthorName if you leave it blank, but you can set it to arbitrary text
    author = "Ziox"
    title = "ZIOX DEMO"
    description = "A hugo site using Edidor. <br/><br/> Ctrl+B toggle sidebar. "
    # change it to false if you don't need syntax highlighting, and save a little bandwidth
    isHighlightCode = true
    # set true need to use custom js
    useCustomSyntaxHighlight = false
    customJs = []
    customCss = []
    mode = "light"
# menubar setting, you can change url, weight and name except the 'Theme'.
[[menu.main]]
    name = "Article"
    url = "#"
    weight = 1
[[menu.main]]
    name = "View"
    url = "#"
    weight = 10
# You can change the name, but please don't edit the identifier
[[menu.main]]
    parent = "View"
    identifier = "toggle-sidebar"
    name = "Toggle Sidebar"
    url = "#"
    weight = 10
[[menu.main]]
    parent = "Article"
    name = "Posts"
    url = "/posts"
    weight = 1
[[menu.main]]
    parent = "Article"
    name = "Tags"
    url = "/tags"
    weight = 20
[[menu.main]]
    parent = "Article"
    name = "Categories"
    url = "/categories"
    weight = 30

# Please don't edit the identifier
# I can't make the identifier works on top menu so please don't change the name of 'Theme' at the moment
[[menu.main]]
    name = "Theme"
    url = "#"
    weight = 25
[[menu.main]]
    parent = "Theme"
    identifier = "light"
    name = "Light"
    url = "#"
    weight = 1
[[menu.main]]
    parent = "Theme"
    identifier = "dark"
    name = "Dark"
    url = "#"
    weight = 10
[[menu.main]]
    parent = "Theme"
    identifier = "wild"
    name = "Wild"
    url = "#"
    weight = 20
[[menu.main]]
    parent = "Theme"
    identifier = "export-wild"
    name = "Export Wild Style"
    url = "#"
    weight = 25
